version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: compufix_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: compufix
      POSTGRES_PASSWORD: compufix_local
      POSTGRES_DB: compufix
    ports:
      - "5432:5432"
    volumes:
      - compufix_pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: compufix_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  compufix_pg_data:
